spring.application.name=kitetech-elearning-be

# DataSource
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/university?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root_password

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Custom API prefix
api.prefix=/api/v1
